[package]
name = "orbutils"
description = "The Orbital Utilities"
repository = "https://gitlab.redox-os.org/redox-os/orbutils"
version = "0.1.16"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[[bin]]
name = "background"
path = "src/background/main.rs"

[[bin]]
name = "calculator"
path = "src/calculator/main.rs"

[[bin]]
name = "character_map"
path = "src/character_map/main.rs"

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[[bin]]
name = "file_manager"
path = "src/file_manager/main.rs"

[[bin]]
name = "launcher"
path = "src/launcher/main.rs"

[[bin]]
name = "orblogin"
path = "src/orblogin/main.rs"

[[bin]]
name = "viewer"
path = "src/viewer/main.rs"

[[bin]]
name = "calendar"
path = "src/calendar/main.rs"

[dependencies]
calculate = { git = "https://gitlab.redox-os.org/redox-os/calc.git" }
chrono = "0.4.6"
mime_guess = "1.8.6"
mime = "0.2.6"
orbclient = "0.3.30"
orbfont = "0.1.8"
orbimage = "0.1.17"
orbtk = "0.2.29"
redox_users = "0.4"

[target.'cfg(not(target_os = "redox"))'.dependencies]
libc = "0.2.50"

[target.'cfg(target_os = "redox")'.dependencies]
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.2.9"
